version: '3'

services:
    ansible:
        build:
            context: ./ansible
        container_name: ansible
        container_name: ansible
        networks:
            - mynetwork
        volumes:
            - ./ansible/ansible_cfg/:/etc/ansible/
            - ./ansible/projectToTest:/home/projectToTest
            - ./ansible/jenkins_home:/var/jenkins_home
        
    raspberry1:
        build:
            context: ./raspberry
        container_name: raspberry1
        networks:
            - mynetwork
        volumes:
            - ./raspberry/volume1:/sdcard
        ports:
            - "2201:2222"

    raspberry2:
        build:
            context: ./raspberry
        container_name: raspberry2
        networks:
            - mynetwork
        volumes:
            - ./raspberry/volume2:/sdcard
        ports:
            - "2202:2222"

    raspberry3:
        build:
            context: ./raspberry
        container_name: raspberry3
        networks:
            - mynetwork
        volumes:
            - ./raspberry/volume3:/sdcard
        ports:
            - "2203:2222"

networks:
  mynetwork:
      driver: bridge