---
- name: Reboot Pi...
  hosts: raspberry-cluster
  gather_facts: no
  tasks:
    - name: Reboot Pi...
      shell: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - name: Wait for reboot...
      local_action: wait_for host={{ ansible_host }}state=started delay=10
      become: false
