---
- name: Shutdown Pi...
  hosts: raspberry-cluster
  gather_facts: no
  tasks:
    - name: 'Shutdown Pi'
      shell: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - name: "Wait for shutdown..."
      local_action: wait_for host={{ ansible_host }} state=stopped
      become: false
